# Server configuration
bind:
  ip: ''
  port: 25565

maxPlayers: 100

ping:
  description: '{""text"": ""&aSurvival &7| &bSkyBlock &7| &eBedWars""}'
  version: '1.21.4'
  protocol: -1

dimension: THE_END

playerList:
  enable: false
  username: 'Steve'

headerAndFooter:
  enable: false
  header: '{""text"": ""&eWelcome!""}'
  footer: '{""text"": ""&9MyServer""}'

gameMode: 3

brandName:
  enable: true
  content: 'vanilla'

joinMessage:
  enable: true
  text: '{""text"": ""&eWelcome to the server!""}'

bossBar:
  enable: true
  text: '{""text"": ""Welcome to the server!""}'
  health: 1.0
  color: PINK
  division: SOLID

title:
  enable: true
  title: '{""text"": ""&9&lWelcome!""}'
  subtitle: '{""text"": ""&6MyServer""}'
  fadeIn: 10
  stay: 100
  fadeOut: 10

infoForwarding:
  type: NONE
  secret: '<YOUR_SECRET_HERE>'
  tokens:
    - '<BUNGEE_GUARD_TOKEN>'

readTimeout: 30000

debugLevel: 2

netty:
  useEpoll: true
  threads:
    bossGroup: 1
    workerGroup: 4

traffic:
  enable: false
  maxPacketSize: 8192
  interval: 7.0
  maxPacketRate: 500.0
